### ISSUE TITLE
"NoSuchBeanDefinitionException: No bean named 'reactors' is defined" on startup

### ISSUE THREAD

**Issue by fill0llif** [fill0llif/yayoi#1]
Executing the app without any components to register leads to the above mentioned error.
Log:

> [2018-10-29T17:11:59.465+01:00] INFO [it.feelburst.yayoi] Application startup...
[2018-10-29T17:11:59.873+01:00] INFO [it.feelburst.yayoi] Framework implementation 'value it.feelburst.yayoi.model::swingFramework' found.
[2018-10-29T17:12:00.388+01:00] INFO [it.feelburst.yayoi] Registering components...
[2018-10-29T17:12:00.389+01:00] INFO [it.feelburst.yayoi] Base package 'package it.feelburst.takane.dashboard' found.
[2018-10-29T17:12:00.389+01:00] INFO [it.feelburst.yayoi] Base package 'package it.feelburst.takane.workspace' found.
[2018-10-29T17:12:00.440+01:00] INFO [it.feelburst.yayoi] Executing reactions...
ceylon run: No bean named 'reactors' is defined
org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'reactors' is defined
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:702)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1180)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:284)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1082)
	at it.feelburst.yayoi.behaviour.component.Context$impl.values(Context.ceylon:27)
	at it.feelburst.yayoi.behaviour.component.impl.NameContext.values(NameContext.ceylon)
	at it.feelburst.yayoi.Yayoi.executeReaction$priv$(Yayoi.ceylon:158)
	at it.feelburst.yayoi.Yayoi.run(Yayoi.ceylon:128)
	at it.feelburst.takane.run_.run(run.ceylon:5)
	at it.feelburst.takane.run_.main(run.ceylon)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.redhat.ceylon.compiler.java.runtime.tools.impl.JavaRunnerImpl.invokeMain(JavaRunnerImpl.java:93)
	at com.redhat.ceylon.compiler.java.runtime.tools.impl.JavaRunnerImpl.run(JavaRunnerImpl.java:61)
	at ceylon.modules.bootstrap.CeylonRunTool.startInFlatClasspath(CeylonRunTool.java:424)
	at ceylon.modules.bootstrap.CeylonRunTool.run(CeylonRunTool.java:289)
	at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:547)
	at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:423)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:108)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:38)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:31)
	at com.redhat.ceylon.launcher.Launcher.main(Launcher.java:24)

**Comment by fill0llif** [comment]
Contains bean check was missing in it.feelburst.yayoi.behaviour.component.Context.
