### ISSUE TITLE
"NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.context.ApplicationEventPublisher] is defined" on startup

### ISSUE THREAD

**Issue by fill0llif** [fill0llif/yayoi#2]
Executing the app without any components to register leads to the above mentioned error.
**This happens only with #1 closed**.
Log:

> [2018-10-29T17:57:19.212+01:00] INFO [it.feelburst.yayoi] Application startup...
[2018-10-29T17:57:19.626+01:00] INFO [it.feelburst.yayoi] Framework implementation 'value it.feelburst.yayoi.model::swingFramework' found.
[2018-10-29T17:57:20.120+01:00] INFO [it.feelburst.yayoi] Registering components...
[2018-10-29T17:57:20.121+01:00] INFO [it.feelburst.yayoi] Base package 'package it.feelburst.takane.dashboard' found.
[2018-10-29T17:57:20.121+01:00] INFO [it.feelburst.yayoi] Base package 'package it.feelburst.takane.workspace' found.
[2018-10-29T17:57:20.162+01:00] INFO [it.feelburst.yayoi] Executing reactions...
[2018-10-29T17:57:20.163+01:00] INFO [it.feelburst.yayoi] Executing actions...
[2018-10-29T17:57:20.163+01:00] INFO [it.feelburst.yayoi] Registering app...
[2018-10-29T17:57:20.167+01:00] INFO [it.feelburst.yayoi] Running app...
[2018-10-29T17:57:20.267+01:00] INFO [it.feelburst.yayoi] Waiting for window to close...
ceylon run: No qualifying bean of type [org.springframework.context.
ApplicationEventPublisher] is defined
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.context.ApplicationEventPublisher] is defined
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:374)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:334)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1088)
	at it.feelburst.yayoi.Yayoi.run(Yayoi.ceylon:135)
	at it.feelburst.takane.run_.run(run.ceylon:5)
	at it.feelburst.takane.run_.main(run.ceylon)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.redhat.ceylon.compiler.java.runtime.tools.impl.JavaRunnerImpl.invokeMain(JavaRunnerImpl.java:93)
	at com.redhat.ceylon.compiler.java.runtime.tools.impl.JavaRunnerImpl.run(JavaRunnerImpl.java:61)
	at ceylon.modules.bootstrap.CeylonRunTool.startInFlatClasspath(CeylonRunTool.java:424)
	at ceylon.modules.bootstrap.CeylonRunTool.run(CeylonRunTool.java:289)
	at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:547)
	at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:423)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:108)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:38)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:31)
	at com.redhat.ceylon.launcher.Launcher.main(Launcher.java:24)

**Comment by fill0llif** [comment]
Spring probably needs to register at least a bean definition containing an autowired ApplicationEventPublisher to actually register it.
**Didn't check on docs but this patch is working.**
